version: '3'
services:
  web:
    image: jacer7/weather_app:latest
    ports:
      - "8000:8000"
    volumes:
      - ./app:/workdir  # Mount local app directory into the container
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
